package br.com.anymarket.sdk.util;

import java.util.HashMap;
import java.util.Map;

/**
 * Recupera o país através do seu código
 */
public class CountryCodes {

    private static final Map<String, String> PAISES = new HashMap<String, String>() {{
        put("AF","Afeganistão");
        put("ZA","África do Sul");
        put("AL","Albânia");
        put("DE","Alemanha");
        put("DZ","Argélia");
        put("AD","Andorra");
        put("AO","Angola");
        put("AI","Anguila");
        put("AQ","Antárctica");
        put("AG","Antígua e Barbuda");
        put("AN","Antilhas Holandesas");
        put("SA","Arábia Saudita");
        put("AR","Argentina");
        put("AM","Arménia");
        put("AW","Aruba");
        put("AU","Austrália");
        put("AT","Áustria");
        put("AZ","Azerbaijão");
        put("BS","Bahamas");
        put("BD","Bangladesh");
        put("BB","Barbados");
        put("BH","Barém");
        put("BE","Bélgica");
        put("BZ","Belize");
        put("BJ","Benin");
        put("BM","Bermuda");
        put("BY","Bielorrússia");
        put("BO","Bolívia");
        put("BA","Bósnia e Herzegovina");
        put("BW","Botswana");
        put("BR","Brasil");
        put("BN","Brunei Darussalam");
        put("BG","Bulgária");
        put("BF","Burkina Faso");
        put("BI","Burundi");
        put("BT","Butão");
        put("CV","Cabo Verde");
        put("CM","Camarões");
        put("KH","Camboja");
        put("CA","Canadá");
        put("QA","Catar");
        put("KZ","Cazaquistão");
        put("CF","Centro-Africana (República) Central African Republic");
        put("TD","Chade");
        put("CL","Chile");
        put("CN","China");
        put("CY","Chipre");
        put("CO","Colômbia");
        put("KM","Comores");
        put("CG","Congo");
        put("CD","Congo (República Democrático do Congo)");
        put("KR","Coreia (República da)");
        put("KP","Coreia (República Popular Democrática da)");
        put("CI","Costa do Marfim");
        put("CR","Costa Rica");
        put("HR","Croácia");
        put("CU","Cuba");
        put("DK","Dinamarca");
        put("DM","Domínica");
        put("EG","Egipto");
        put("SV","El Salvador");
        put("AE","Emiratos Árabes Unidos");
        put("EC","Equador");
        put("ER","Eritreia");
        put("SK","Eslovaca (República)");
        put("SI","Eslovénia");
        put("ES","Espanha");
        put("US","Estados Unidos");
        put("EE","Estónia");
        put("ET","Etiópia");
        put("PH","Filipinas");
        put("FI","Finlândia");
        put("FR","França");
        put("GA","Gabão");
        put("GM","Gâmbia");
        put("GH","Gana");
        put("GE","Geórgia");
        put("GS","Geórgia do Sul e Ilhas Sandwich");
        put("GI","Gibraltar");
        put("GD","Granada");
        put("GR","Grécia");
        put("GL","Gronelândia");
        put("GP","Guadalupe");
        put("GU","Guam");
        put("GT","Guatemala");
        put("GY","Guiana");
        put("GF","Guiana Francesa");
        put("GN","Guiné");
        put("GQ","Guiné Equatorial");
        put("GW","Guiné-Bissau");
        put("HT","Haiti");
        put("HN","Honduras");
        put("HK","Hong Kong");
        put("HU","Hungria");
        put("YE","Iémen");
        put("BV","Ilhas Bouvet");
        put("KY","Ilhas Caimão");
        put("CX","Ilhas Christmas");
        put("CC","Ilhas Cocos (Keeling)");
        put("CK","Ilhas Cook");
        put("FK","Ilhas Falkland (Malvinas)");
        put("FO","Ilhas Faroé");
        put("FJ","Ilhas Fiji");
        put("HM","Ilhas Heard e Ilhas McDonald");
        put("MP","Ilhas Marianas do Norte");
        put("MH","Ilhas Marshall");
        put("UM","Ilhas Menores Distantes dos Estados Unidos");
        put("NF","Ilhas Norfolk");
        put("SB","Ilhas Salomão");
        put("VG","Ilhas Virgens (britânicas)");
        put("VI","Ilhas Virgens (Estados Unidos)");
        put("IN","Índia");
        put("ID","Indonésia");
        put("IR","Irão (República Islâmica)");
        put("IQ","Iraque");
        put("IE","Irlanda");
        put("IS","Islândia");
        put("IL","Israel");
        put("IT","Itália");
        put("JM","Jamaica");
        put("JP","Japão");
        put("DJ","Jibuti");
        put("JO","Jordânia");
        put("YU","Jugoslávia");
        put("KE","Kenya");
        put("KI","Kiribati");
        put("KW","Kuwait");
        put("LA","Laos (República Popular Democrática do)");
        put("LS","Lesoto");
        put("LV","Letónia");
        put("LB","Líbano");
        put("LR","Libéria");
        put("LY","Líbia (Jamahiriya Árabe da)");
        put("LI","Liechtenstein");
        put("LT","Lituânia");
        put("LU","Luxemburgo");
        put("MO","Macau");
        put("MK","Macedónia (Antiga República Jugoslava da)");
        put("MG","Madagáscar");
        put("MY","Malásia");
        put("MW","Malawi");
        put("MV","Maldivas");
        put("ML","Mali");
        put("MT","Malta");
        put("MA","Marrocos");
        put("MQ","Martinica");
        put("MU","Maurícias");
        put("MR","Mauritânia");
        put("YT","Mayotte");
        put("MX","México");
        put("FM","Micronésia (Estados Federados da)");
        put("MZ","Moçambique");
        put("MD","Moldova (República de)");
        put("MC","Mónaco");
        put("MN","Mongólia");
        put("MS","Monserrate");
        put("MM","Myanmar");
        put("NA","Namíbia");
        put("NR","Nauru");
        put("NP","Nepal");
        put("NI","Nicarágua");
        put("NE","Niger");
        put("NG","Nigéria");
        put("NU","Niue");
        put("NO","Noruega");
        put("NC","Nova Caledónia");
        put("NZ","Nova Zelândia");
        put("OM","Omã");
        put("NL","Países Baixos");
        put("PW","Palau");
        put("PA","Panamá");
        put("PG","Papuásia-Nova Guiné");
        put("PK","Paquistão");
        put("PY","Paraguai");
        put("PE","Peru");
        put("PN","Pitcairn");
        put("PF","Polinésia Francesa");
        put("PL","Polónia");
        put("PR","Porto Rico");
        put("PT","Portugal");
        put("KG","Quirguizistão");
        put("GB","Reino Unido");
        put("CZ","República Checa");
        put("DO","República Dominicana");
        put("RE","Reunião");
        put("RO","Roménia");
        put("RW","Ruanda");
        put("RU","Rússia (Federação da)");
        put("WS","Samoa");
        put("AS","Samoa Americana");
        put("SH","Santa Helena");
        put("LC","Santa Lúcia");
        put("VA","Santa Sé (Cidade Estado do Vaticano) (*)");
        put("KN","São Cristóvão e Nevis");
        put("SM","São Marino");
        put("PM","São Pedro e Miquelon");
        put("ST","São Tomé e Príncipe");
        put("VC","São Vicente e Granadinas");
        put("EH","Sara Ocidental");
        put("SN","Senegal");
        put("SL","Serra Leoa");
        put("SC","Seychelles");
        put("SG","Singapura");
        put("SY","Síria (República Árabe da)");
        put("SO","Somália");
        put("LK","Sri Lanka");
        put("SZ","Suazilândia");
        put("SD","Sudão");
        put("SE","Suécia");
        put("CH","Suíça");
        put("SR","Suriname");
        put("SJ","Svålbard e a Ilha de Jan Mayen");
        put("TH","Tailândia");
        put("TW","Taiwan (Província da China)");
        put("TJ","Tajiquistão");
        put("TZ","Tanzânia, República Unida da");
        put("IO","Território Britânico do Oceano Índico");
        put("PS","Território Palestiniano Ocupado");
        put("TF","Territórios Franceses do Sul");
        put("TP","Timor Leste");
        put("TG","Togo");
        put("TK","Tokelau");
        put("TO","Tonga");
        put("TT","Trindade e Tobago");
        put("TN","Tunísia");
        put("TC","Turcos e Caicos (Ilhas)");
        put("TM","Turquemenistão");
        put("TR","Turquia");
        put("TV","Tuvalu");
        put("UA","Ucrânia");
        put("UG","Uganda");
        put("UY","Uruguai");
        put("UZ","Usbequistão");
        put("VU","Vanuatu");
        put("VE","Venezuela");
        put("VN","Vietname");
        put("WF","Wallis e Futuna (Ilha)");
        put("ZM","Zâmbia");
        put("ZW","Zimbabwe");
    }};

    public static String getCountryName(String code) {
        return PAISES.get(code);
    }

}
