package br.com.anymarket.sdk;

public enum MarketPlace {
    CNOVA("Via Varejo"),
    MAGENTO("Magento"),
    MERCADO_LIVRE("Mercado Livre"),
    B2W("B2W"),
    ECOMMERCE("E-Commerce"),
    WALMART("Walmart"),
    VTEX("VTEX"),
    GFG("GFG - Dafiti"),
    LINIO("Linio"),
    NETSHOES("Netshoes"),
    MAGAZINE_LUIZA("Magazine Luiza"),
    CARREFOUR("Carrefour"),
    AMAZON("Amazon"),
    BUSCAPE("Buscapé"),
    ORACLECOMMERCE("Oracle Commerce Cloud"),
    MADEIRA_MADEIRA("Madeira Madeira"),
    CISSA_MAGAZINE("Cissa Magazine"),
    B2W_NEW_API("B2W Nova API"),
    SARAIVA("Saraiva"),
    HUB_SALES("Hub Sales"),
    ZOOM("Zoom"),
    WEB_CONTINENTAL("Web Continental"),
    RICARDO_ELETRO("Ricardo Eletro"),
    CENTAURO("Centauro"),
    PORTAL_DO_MEDICO("Portal do Médico"),
    TRAY("Tray"),
    CAMICADO("Camicado"),
    GALITHX("Go Core Marketplace (Galithx e Gorila Z)"),
    COLOMBO("Lojas Colombo"),
    DIA_GROUP("Dia Group"),
    ELETRUM("Eletrum"),
    OPTEMAIS("Optemais"),
    EFACIL("eFácil"),
    LEROY_MERLIN("Leroy Merlin"),
    COBASI("Cobasi"),
    CATWALK("Catwalk"),
    CASA_SHOW("BRHC"),
    WISH("Wish"),
    MOBLY("Mobly"),
    HOME_TO_GO("Home To Go"),
    CONNECT_PARTS("Connect Parts"),
    GARBARINO("Garbarino"),
    NOVO_MUNDO("Novo Mundo"),
    POSTHAUS("Posthaus"),
    MARABRAZ("Marabraz"),
    LOJA_VIVO("Loja Vivo"),
    ESTANTE_VIRTUAL("Estante Virtual"),
    RI_HAPPY("Ri Happy"),
    FAST_SHOP("Fast Shop"),
    CYBELAR("Cybelar"),
    CLUBE_DE_MARCAS("Clube de Marcas"),
    C_A("C&A"),
    ICBC_MALL("ICBC Mall"),
    TIENDA_SUPERVIELLE("Tienda Supervielle"),
    TIENDA_CLIC("Tienda Clic"),
    QISAR("Qisar"),
    CLAROPROMO("Claropromo"),
    BALCAO_RURAL("Balcao Rural"),
    CENTAURO_NEW_API("Centauro Nova API"),
    KABUM("Kabum"),
    MULTIVAREJO_GPA("Multivarejo GPA"),
    NUVEMSHOP("Nuvemshop"),
    LOJAS_LEBES("Lojas Lebes"),
    DROGA_RAIA("Droga Raia"),
    PASSARELA("Passarela"),
    AVENIDA("Avenida"),
    TIENDA_NARANJA("Tienda Naranja"),
    BANCO_INTER("Banco Inter"),
    HAVAN("Havan"),
    MARKETPLACE_TESTE("Marketplace Teste"),
    ETNA("Etna"),
    WEB_CONTINENTAL_NEW_API("Web Continental Nova API"),
    ELETROSOM("Eletrosom"),
    QUERO_QUERO("Quero-Quero"),
    COMPRA_CERTA("Compra Certa"),
    ARMAZEM_PARAIBA("Armazém Paraíba"),
    RIACHUELO("Riachuelo"),
    CONECTA_LA("Conecta La"),
    OLIST("OLIST"),
    RENNER("Renner"),
    AJPLACE("AJPlace"),
    CREDITAS("Creditas"),
    SHOPEE("Shopee"),
    CASSOL_CENTERLAR("Cassol Centerlar"),
    MAXMANIA("Maxmania"),
    ONSTORES("ONSTORES"),
    HOMEREFILL("Homerefill"),
    DOTZ("Dotz"),
    DECATHLON("Decathlon");

    private String name;

    private MarketPlace(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.name;
    }
}
